@startmindmap OS
 
+ 操作系统


-- 硬件管理
--- 设备管理
---- CPU
---- 内存
---- 外存

++ 软件接口
+++ 文件系统

+++ 存储管理
++++ 缘由:受限于内存的高性能与高价(与外存对比)---追求性能
++++ 抽象目标
+++++ 虚拟存储器:\n---对每一个程序而言，\n拥有无限大、无限快的存储器
++++ 内存管理
+++++ 系统视角
++++++ 分配与回收
++++++ 内存信息的共享与保护
++++++ 虚拟地址与物理地址之间的变换---存储器的抽象
++++++ 内、外存之间的数据交换---实现无限大
+++++ 应用程序视角的实现手段
++++++ 分区
+++++++ 分区类型
+++++++ 分区算法
++++++ 分页
++++++ 分段


+++ 进程管理
+++ 网络管理


@endmindmap