
DEMO_DRIVER_PATH = Drivers/demo_driver

C_SOURCES += \
	$(DEMO_DRIVER_PATH)/gpio/gpio.c \
	$(DEMO_DRIVER_PATH)/rcc/rcc.c \


C_INCLUDES += \
	-I$(DEMO_DRIVER_PATH) \
	-I$(DEMO_DRIVER_PATH)/gpio \
	-I$(DEMO_DRIVER_PATH)/rcc \
	-I$(DEMO_DRIVER_PATH)/usart \

